/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as LineamentsRouteImport } from './routes/lineaments'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const LineamentsRoute = LineamentsRouteImport.update({
  id: '/lineaments',
  path: '/lineaments',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/exports': typeof ExportsRoute
  '/history': typeof HistoryRoute
  '/lineaments': typeof LineamentsRoute
  '/provider': typeof ProviderRoute
  '/questions': typeof QuestionsRoute
  '/validation': typeof ValidationRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/exports': typeof ExportsRoute
  '/history': typeof HistoryRoute
  '/lineaments': typeof LineamentsRoute
  '/provider': typeof ProviderRoute
  '/questions': typeof QuestionsRoute
  '/validation': typeof ValidationRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/exports': typeof ExportsRoute
  '/history': typeof HistoryRoute
  '/lineaments': typeof LineamentsRoute
  '/provider': typeof ProviderRoute
  '/questions': typeof QuestionsRoute
  '/validation': typeof ValidationRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/exports'
    | '/history'
    | '/lineaments'
    | '/provider'
    | '/questions'
    | '/validation'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/exports'
    | '/history'
    | '/lineaments'
    | '/provider'
    | '/questions'
    | '/validation'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/exports'
    | '/history'
    | '/lineaments'
    | '/provider'
    | '/questions'
    | '/validation'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  ExportsRoute: typeof ExportsRoute
  HistoryRoute: typeof HistoryRoute
  LineamentsRoute: typeof LineamentsRoute
  ProviderRoute: typeof ProviderRoute
  QuestionsRoute: typeof QuestionsRoute
  ValidationRoute: typeof ValidationRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineaments': {
      id: '/lineaments'
      path: '/lineaments'
      fullPath: '/lineaments'
      preLoaderRoute: typeof LineamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  ExportsRoute: ExportsRoute,
  HistoryRoute: HistoryRoute,
  LineamentsRoute: LineamentsRoute,
  ProviderRoute: ProviderRoute,
  QuestionsRoute: QuestionsRoute,
  ValidationRoute: ValidationRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
